[package]
name = "jj"
version = "0.1.0"
edition.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
jj-lib.workspace = true
log.workspace = true
util.workspace = true
